![ADSA Logo](http://i.imgur.com/BV0CdHZ.png?2 "ADSA Logo")

# ADSA Workshop 2 - Diving Deeper into Python
> Workshop content adapted from
* https://github.com/ehmatthes/intro_programming/
* http://github.com/rasbt/python_reference/blob/master/tutorials/sorting_csvs.ipynb
* http://www.engr.ucsb.edu/~shell/che210d/numpy.pdf

This code imports the testing library and modifies the print command to work as a regular Python function

In [1]:
from test_helper import Test
from __future__ import print_function

## Refresher of Workshop 1

In the first workshop (accessible here: https://github.com/ADSA-UIUC/PythonWorkshop_1/), we learned the following topics:

### Comments

In [2]:
# Any line that starts with a '#' is a comment.
# print('This line is a comment, so it gets executed.')

print('This line is not a comment, so it gets executed.')

This line is not a comment, so it gets executed.


### Variables: Strings and Numbers

In [3]:
# declare a string
my_str = 'Strings are enclosed by single- or double-quotes.'

# declare some integers
a = 7
b = 2.3
c = a * b
d = a + c

# operations on numbers
print('c is equal to {0}, d is equal to {1}'.format(c, d))

c is equal to 16.1, d is equal to 23.1


### If-else Conditionals

In [4]:
if 35 >= 17:
    print("Condition is True")
else:
    print("Condition is False")
print("Condition is True or False, either way this is outputted")

Condition is True
Condition is True or False, either way this is outputted


### Lists and Loops

In [5]:
awesome_people = ["Eric Idle", "John Cleese", "Albert Fry"]
print(awesome_people)

['Eric Idle', 'John Cleese', 'Albert Fry']


In [6]:
for number in range(0, 5):
    print("I am on iteration {0}!".format(number))

I am on iteration 0!
I am on iteration 1!
I am on iteration 2!
I am on iteration 3!
I am on iteration 4!


***
## Functions

Functions are a set of actions that we group together, and give a name to. We can define our own functions, which allows us to "teach" Python new behavior.

Here is the general syntax for defining and calling functions.

    # Let's define a function.
    def function_name(argument_1, argument_2):
        # Do whatever we want this function to do,
        #  using argument_1 and argument_2

    # Use function_name to call the function.
    function_name(value_1, value_2)

* __Defining a function__
    * The keyword `def` tells Python that you are about to define a function.
    * Functions have a name. A variable name tells you what kind of value the variable contains; a function name should tell you what the function does.
    * The values inside parentheses are called __arguments__ or __parameters__. Functions use parameters to get data it may need to execute.
        * These are basically variable names, but they are only used in the function.
        * They can be different names than what you use in the rest of your program.
    * Make sure the function definition line ends with a colon.
* __Using your function__
    * To call your function, write its name followed by parentheses.
    * Inside the parentheses, provide the values for the function's parameters.
    * These can be values can be other variables you have defined or literal values.

In [7]:
# This function prints a two-line personalized thank you message.
def thank_you(name):
    # print() is also a function!
    # It prints the string you give it onto the screen.
    
    print('You are doing good work, {0}!'.format(name))
    print('Thank you very much for your efforts on this project.\n')

In [8]:
# now we can use the function that we just defined

thank_you('Adriana')
thank_you('Billy')
thank_you('Caroline')

You are doing good work, Adriana!
Thank you very much for your efforts on this project.

You are doing good work, Billy!
Thank you very much for your efforts on this project.

You are doing good work, Caroline!
Thank you very much for your efforts on this project.



In [9]:
students = ['Bernice', 'Aaron', 'Cody']

# Use the sort function to put students in alphabetical order.
students.sort()

# Display the list in its current order.
print("Students in alphabetical order.")
for student in students:
    print(student.title())

# Give the sort function the reverse parameter
# This puts students in reverse alphabetical order.
students.sort(reverse=True)

# Display the list in reverse order.
print("\nStudents in reverse alphabetical order.")
for student in students:
    print(student.title())

Students in alphabetical order.
Aaron
Bernice
Cody

Students in reverse alphabetical order.
Cody
Bernice
Aaron


### Advantages of using functions
You might be able to see some advantages of using functions:
* We can write a set of instructions once and use it as many times as we want without retyping it.
* When our function works, we don't have to worry about that code anymore. Every time you repeat code in your program, you introduce an opportunity to make a mistake. Writing code in functions means the any possible errors are localized. And when those bugs are fixed, we can be confident that the function will continue to work correctly.
* We can modify our function's behavior once, and that change takes effect every time the function is called. This is much better than deciding we need some new behavior, and then having to change code in many different places in our program.

### Returning Values from Functions

Each function you create can return a value. This can be in addition to the primary work the function does, or it can be the function's main job. The following function takes in a number, and returns the corresponding word for that number:

In [10]:
def get_number_word(number):
    # Takes in a numerical value, and returns the word corresponding to that number.
    if number == 1:
        return 'one'
    elif number == 2:
        return 'two'
    elif number == 3:
        return 'three'
    
# Let's try out our function.
for number in range(0, 4):
    number_word = get_number_word(number)
    print(number, number_word)

0 None
1 one
2 two
3 three


In [11]:
def add_five(number):
    print("Adding 5 to", number, "now...")
    return number + 5
    print("This will not get printed")
    
# Now use your function add_five()
num = add_five(10)
print("New number is:", num)

Adding 5 to 10 now...
New number is: 15


***
## Dictionaries

Dictionaries allow us to store connected bits of information. For example, you might store a person's name and age together. They store information in key-value pairs, so that any one piece of information in a dictionary is connected to at least one other piece of information.

The general syntax of how dictionaries are declared are:

`dictionary_name = {key_1: value_1, key_2: value_2, key_3: value_3}`

### Adding and Accessing Key-Value Pairs

In [12]:
# Create an empty dictionary.
pets = {}

# Fill the dictionary, pair by pair.
pets['Willie'] ='dog'
pets['Schroedinger'] = 'cat'
pets['Zinga'] = 'hamster'

# Print out the items in the dictionary.
for name, animal in pets.items():
    print(name, 'is a', animal)

Willie is a dog
Schroedinger is a cat
Zinga is a hamster


Removing key-value pairs from a dictionary is done using the `del` keyword:

In [13]:
del pets['Zinga']

print(pets)

{'Willie': 'dog', 'Schroedinger': 'cat'}


The key-value format of the dictionary data structure is actually quite accessible. Usually, data on the internet obtained from APIs follow the JSON format and their similar structure to dictionaries allows us to easily convert between JSON data and dictionaries.

***
## A Look at the Python Standard Library

Python comes "batteries loaded". This means that Python comes with a lot of prewritten code that is called the standard library. This library is very extensive, and offers a lot of modules and classes to accomplish a wide range of tasks.

All of the modules in Python 2.7's Standard Library are listed in the official documentation at https://docs.python.org/2/library/index.html. To use any of these modules, you need to import them or the specific functions in them:

    import math
    from math import factorial, log

Now we are going to look at some functions in the String and Regex modules.

### Strings and Math

The `string` module is imported by default, so all string functions are always accessible. The availble string functions are listed here: https://docs.python.org/2/library/stdtypes.html#string-methods.

In [14]:
str = 'Hi! My name is Python!'

# convert the string to uppercase letters
print(str.upper())

# convert all lowercase letters to uppercase and vice versa
print(str.swapcase())

# check if a string is a digit(s) or not
print( "83".isdigit() )

HI! MY NAME IS PYTHON!
hI! mY NAME IS pYTHON!
True


The `math` module's functions are listed here: https://docs.python.org/2/library/math.html

In [15]:
import math

mynum = 14
print(math.sqrt(mynum))

# math.pi is a constant in the math module
print( math.sin(math.pi) ) # should be almost 0

3.74165738677
1.22464679915e-16


### Parsing CSV Files

The CSV (Comma Separated Values) format is the most common import and export format for spreadsheets and databases. Although there is no standard for how the data is formatted, the generally followed format is like so:

    column1_title, column2_title, column3_title
    row1_data1, row1_data2, row1_data3
    row2_data1, row2_data2, row2_data3
    ...

While the delimiters and quoting characters vary, the overall format is similar enough for easy parsing using the `csv` module.

In the `data` folder, there is a `test.csv` file with the following contents:

    name,column1,column2,column3
    abc,1.1,4.2,1.2
    def,2.1,1.4,5.2
    ghi,1.5,1.2,2.1
    jkl,1.8,1.1,4.2
    mno,9.4,6.6,6.2
    pqr,1.4,8.3,8.4
    
Let's see how to parse the file and read the first few lines.

In [16]:
import csv

# the relative path to the location of our csv file
csv_file = 'data/test.csv'

# a blank object that will store the parsed csv data
test_csv = None

# Whenever you call the open() function in Python,
# you also need to call the close function. But since
# a lot of people forget, the general syntax people
# use is the "with as" structure.
# In the case below, the file contents that the
# open() function returns is stored in a temporary
# variable called csv_con.
with open(csv_file, 'r') as csv_con:
    # create a reader variable to read and parse csv_con
    reader = csv.reader(csv_con, delimiter=',')
    # store the parsed data as a list in test_csv
    test_csv = list(reader)

print('First 3 rows:')
for row in range(3):
    print(test_csv[row])

First 3 rows:
['name', 'column1', 'column2', 'column3']
['abc', '1.1', '4.2', '1.2']
['def', '2.1', '1.4', '5.2']


### Accessing the web using `urllib2`

`urllib2` is a very easy-to-use module to fetch URLs (Uniform Resource Locators). You can use this module to easily read and use web content in your code.

Let's start by seeing what reading the Python.org homepage through urllib2 looks like.

In [17]:
import urllib2
url = 'http://python.org'
response = urllib2.urlopen(url)
html = response.read()

print(html)

<!doctype html>
<!--[if lt IE 7]>   <html class="no-js ie6 lt-ie7 lt-ie8 lt-ie9">   <![endif]-->
<!--[if IE 7]>      <html class="no-js ie7 lt-ie8 lt-ie9">          <![endif]-->
<!--[if IE 8]>      <html class="no-js ie8 lt-ie9">                 <![endif]-->
<!--[if gt IE 8]><!--><html class="no-js" lang="en" dir="ltr">  <!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <link rel="prefetch" href="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js">

    <meta name="application-name" content="Python.org">
    <meta name="msapplication-tooltip" content="The official home of the Python Programming Language">
    <meta name="apple-mobile-web-app-title" content="Python.org">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="HandheldFriendly" conte

This prints out the complete source HTML of the website. We have this data stored as a regular string in the `html` variable, and we can now do whatever we want with it.

***
## Build a Weather Reporting Program!

Let's now use the `urllib2` module to build a small program that tells you the city and the current weather when you give it the zip code of a place.

For the weather data, we will use the service OpenWeatherMap.org. Type the URL http://api.openweathermap.org/data/2.5/weather?zip=61820,us into the address bar in a new tab. The website shows text about the weather information in the area of zipcode 61820 (Champaign). Let's load this information through `urllib2`.

In [18]:
# urllib2 is already imported

url = 'http://api.openweathermap.org/data/2.5/weather?zip=61820,us'
response = urllib2.urlopen(url)
weather_html = response.read()

print(weather_html)

{"coord":{"lon":-88.24,"lat":40.12},"weather":[{"id":800,"main":"Clear","description":"sky is clear","icon":"01d"}],"base":"cmc stations","main":{"temp":292.2,"pressure":1020,"humidity":42,"temp_min":291.15,"temp_max":293.15},"wind":{"speed":3.6,"deg":330},"clouds":{"all":1},"dt":1442160931,"sys":{"type":1,"id":960,"message":0.0034,"country":"US","sunrise":1442143944,"sunset":1442189056},"id":4887158,"name":"Champaign","cod":200}



The string that we have received is formatted in JSON, which is very similar to a Python dictionary. Let's parse this JSON data into a Python dictionary, and also pretty print it so that we can understand the structure of the data.

In [19]:
from json import JSONDecoder, dumps

decoder = JSONDecoder()
weather_data = decoder.decode(weather_html)
pretty_weather_data = dumps(weather_data, sort_keys=True, indent=2, separators=(',', ': '))

print(pretty_weather_data)

{
  "base": "cmc stations",
  "clouds": {
    "all": 1
  },
  "cod": 200,
  "coord": {
    "lat": 40.12,
    "lon": -88.24
  },
  "dt": 1442160931,
  "id": 4887158,
  "main": {
    "humidity": 42,
    "pressure": 1020,
    "temp": 292.2,
    "temp_max": 293.15,
    "temp_min": 291.15
  },
  "name": "Champaign",
  "sys": {
    "country": "US",
    "id": 960,
    "message": 0.0034,
    "sunrise": 1442143944,
    "sunset": 1442189056,
    "type": 1
  },
  "weather": [
    {
      "description": "sky is clear",
      "icon": "01d",
      "id": 800,
      "main": "Clear"
    }
  ],
  "wind": {
    "deg": 330,
    "speed": 3.6
  }
}


The information we want to build our program is the `name` field and the `temp` field which is inside the `main` sub-dictionary.

In [20]:
city = weather_data['name']

temp_kelvin = weather_data['main']['temp']
temp_fah = 1.8 * (temp_kelvin - 273.15) + 32

print("We are in {0} and it is {1} degrees outside!".format(city, temp_fah))

We are in Champaign and it is 66.29 degrees outside!


Let's put all of this into a nice and easy to use function.

In [21]:
def tell_me_weather(zipcode):
    # import urllib2
    
    url = 'http://api.openweathermap.org/data/2.5/weather?zip={0},us'.format(zipcode)
    response = urllib2.urlopen(url)
    weather_html = response.read()
    
    # from json import JSONDecoder, dumps

    decoder = JSONDecoder()
    weather_data = decoder.decode(weather_html)
    
    city = weather_data['name']

    temp_kelvin = weather_data['main']['temp']
    temp_fah = 1.8 * (temp_kelvin - 273.15) + 32

    print("You are in {0} and it is {1} degrees outside!".format(city, temp_fah))

Now let's use our new `tell_me_weather` function!

In [22]:
print( tell_me_weather(60061) )

You are in Vernon Hills and it is 64.778 degrees outside!
None


***
## Getting started with NumPy

NumPy (or Numerical Python), is part of a great set of free scientific computing libraries called SciPy that provide mathematical and numerical functions that work very fast. NumPy is like MATLAB, and you can use it to create very powerful arrays and matrices, and it also has various kinds of optimization algorithms and linear algebra functions that are very useful for data science and analytics

In [23]:
# Let's import numpy to use some of its functions
import numpy as np

The central feature of NumPy is the array object class. Arrays are similar to lists in Python, except that every element of an array must be of the same type, typically a numeric type like `float` or `int`. Arrays make operations with large amounts of numeric data very fast and are generally much more efficient than lists.

In [24]:
my_list = [1, 4, 5, 8]
a = np.array(my_list)

print(a)

[1 4 5 8]


Array elements are accessed, sliced, and manipulated just like lists.

In [25]:
# accessing elements of the array using an index
# return the 4th element in the array (0-indexed!)
print(a[3])

# accessing multiple continuous elements of the array, also called slicing
print(a[:2])

# modifying elements of the array
a[0] = 5
print(a)

8
[1 4]
[5 4 5 8]


Note that the type of `a` is "`ndarray`"

In [26]:
print(type(a))

<type 'numpy.ndarray'>


This means that numpy can handle multi-dimensional arrays. Let's create a 2-dimensional array

In [27]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [28]:
# access the element is the first row, second column
print( b[0, 1] )

2


In [29]:
# slice the array and access only the 3rd column
print( b[:, 2] )

[3 6]


The `shape` property returns the size of each dimension of the array

In [30]:
print( a.shape )
print( b.shape )

(4,)
(2, 3)


The `in` statement can be used to check if values are present in the array

In [31]:
print( 3 in b )

True


In [32]:
print( 7 in a )

False


Arrays can be reshaped to different dimension sizes

In [33]:
a = np.array(range(10), float)
print(a)
print(a.shape)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
(10,)


In [34]:
# reshape (10,) array to (5,2)
a = a.reshape((5, 2))
print(a)
print(a.shape)

[[ 0.  1.]
 [ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]
 [ 8.  9.]]
(5, 2)


We can create special matrices in NumPy too! Remember that they are still referred to as arrays in NumPy.

In [35]:
# create the identity 2-dimensional array of shape (4,4)
i = np.identity(4)
print(i)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [36]:
# create a (3,3) array with all ones
o = np.ones((3,3))
print(o)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


We can even do math operations on these arrays. All of the operations below happen element-wise. To do matrix multiplication and other matrix-specific math, we will have to use NumPy's linear algebra functions.

In [37]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)
print(a)
print(b)

[ 1.  2.  3.]
[ 5.  2.  6.]


In [38]:
print( a + b )

[ 6.  4.  9.]


In [39]:
print( a - b )

[-4.  0. -3.]


In [40]:
print( a * b )

[  5.   4.  18.]


In [41]:
print( b / a )

[ 5.  1.  2.]


In [42]:
print( b ** a)

[   5.    4.  216.]
